### ISSUE TITLE
Add syntax highlighting

### ISSUE THREAD

**Issue by nottrobin** [ubuntudesign/docs.ubuntu.com#28]
Find a way of highlighting syntax in the code blocks.

Try to use the method & colours used in github.

**Comment by yaili** [comment]
Is this not for vanilla-docs-theme-design?

**Comment by nottrobin** [comment]
design? What goes in vanilla-docs-theme-design vs vanilla-docs-theme?

My thinking was that we'll probably, at least to start with, use a standard library of some kind that will add some ugly classes to the markup like "f-p" or something, and then will provide us with some standard CSS to display those with standard highlighting colours.

I assume this is more messy than any CSS we'd want to include in a theme for the time being, so I'd keep it local to docs.ubuntu.com for now, to get a basic version working. We can then consider how to formalise it in a theme.

**Comment by yaili** [comment]
Whether it's part of vanilla-docs-theme or -design, should it not be part of the theme rather than this specific site?
